### ISSUE TITLE
Add a .fasta and .csv for each uk_lineage

### ISSUE THREAD

**Issue by rambaut** [COG-UK/grapevine#60]
Create a .fasta alignment and a .csv subset file that matches each of the trees in `uk_lineages/`. Possibly need to extend fastafunk's `extract` function to be able to use a tree for matching taxa.

**Comment by benjamincjackson** [comment]
@rambaut do you have column preferences for the csv file?

**Comment by rambaut** [comment]
The same columns as the trees/cog_global...csv
